src/Entity/CustomerProduct.php
<?php

namespace App\Entity;

use App\Repository\CustomerProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerProductRepository::class)]
class CustomerProduct
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nr_serie = null;

    #[ORM\ManyToOne(inversedBy: 'customerProducts')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'customerProduct')]
    private ?Product $product = null;

    #[ORM\OneToMany(mappedBy: 'customerProduct', targetEntity: Ticket::class)]
    private Collection $tickets;

    #[ORM\OneToMany(mappedBy: 'customerProduct', targetEntity: TaskProductUser::class)]
    private Collection $taskProductUsers;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->taskProductUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNrSerie(): ?string
    {
        return $this->nr_serie;
    }

    public function setNrSerie(string $nr_serie): self
    {
        $this->nr_serie = $nr_serie;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): self
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setCustomerProduct($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): self
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getCustomerProduct() === $this) {
                $ticket->setCustomerProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, TaskProductUser>
     */
    public function getTaskProductUsers(): Collection
    {
        return $this->taskProductUsers;
    }

    public function addTaskProductUser(TaskProductUser $taskProductUser): self
    {
        if (!$this->taskProductUsers->contains($taskProductUser)) {
            $this->taskProductUsers->add($taskProductUser);
            $taskProductUser->setCustomerProduct($this);
        }

        return $this;
    }

    public function removeTaskProductUser(TaskProductUser $taskProductUser): self
    {
        if ($this->taskProductUsers->removeElement($taskProductUser)) {
            // set the owning side to null (unless already changed)
            if ($taskProductUser->getCustomerProduct() === $this) {
                $taskProductUser->setCustomerProduct(null);
            }
        }

        return $this;
    }
}

templates/customer_product/_delete_form.html.twig
<form method="post" action="{{ path('app_customer_product_delete', {'id': customer_product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ customer_product.id) }}">
    <button class="btn">Delete</button>
</form>

templates/customer_product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/customer_product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit CustomerProduct{% endblock %}

{% block body %}
    <h1>Edit CustomerProduct</h1>

    {{ include('customer_product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_customer_product_index') }}">back to list</a>

    {{ include('customer_product/_delete_form.html.twig') }}
{% endblock %}

templates/customer_product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomerProduct index{% endblock %}

{% block body %}
    <h1>CustomerProduct index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nr_serie</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for customer_product in customer_products %}
            <tr>
                <td>{{ customer_product.id }}</td>
                <td>{{ customer_product.nrSerie }}</td>
                <td>
                    <a href="{{ path('app_customer_product_show', {'id': customer_product.id}) }}">show</a>
                    <a href="{{ path('app_customer_product_edit', {'id': customer_product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_customer_product_new') }}">Create new</a>
{% endblock %}

templates/customer_product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New CustomerProduct{% endblock %}

{% block body %}
    <h1>Create new CustomerProduct</h1>

    {{ include('customer_product/_form.html.twig') }}

    <a href="{{ path('app_customer_product_index') }}">back to list</a>
{% endblock %}

templates/customer_product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}CustomerProduct{% endblock %}

{% block body %}
    <h1>CustomerProduct</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ customer_product.id }}</td>
            </tr>
            <tr>
                <th>Nr_serie</th>
                <td>{{ customer_product.nrSerie }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_customer_product_index') }}">back to list</a>

    <a href="{{ path('app_customer_product_edit', {'id': customer_product.id}) }}">edit</a>

    {{ include('customer_product/_delete_form.html.twig') }}
{% endblock %}